service: aws-python-telegram-bot

provider:
  name: aws
  lambdaHashingVersion: "20201221"
  runtime: python3.8
  profile: default
  environment:
    TELEGRAM_TOKEN: ${file(./serverless.env.yml):TELEGRAM_TOKEN, ''}

layers:
  tesseract:
    path: tesseract_layer
    compatibleRuntimes:
    - python3.8


functions:
  webhook:
    handler: handler.webhook
    layers:
      - { Ref: TesseractLambdaLayer }
    events:
      - http: POST /

  set_webhook:
    handler: handler.set_webhook
    events:
      - http: POST /set_webhook

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    useDownloadCache: true
    useStaticCache: true